name: Post diffs

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  post_diffs:
    uses: Anushka-io/course-sdk/.github/workflows/post-diffs-in-pr.yml@main
    with:
      sdkRef: main
